apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-eks
  region: ap-southeast-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    ssh: # use existing EC2 key
      publicKeyName: eks-capstone